// <auto-generated />
using System;
using AstraGraph.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstraGrpah.Migrations
{
    [DbContext(typeof(AstraDbContext))]
    [Migration("20250219105253_DeleteTables")]
    partial class DeleteTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstraGraph.Models.OrbitalCounts", b =>
                {
                    b.Property<string>("Orbital_Regime")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.HasKey("Orbital_Regime");

                    b.ToTable("OrbitalCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
